#!/bin/bash
# ============================================================
# PURPLE RAINMAKER — Install Script
# Run once after cloning the repo.
# Usage: bash install.sh
# ============================================================

GRN='\033[0;32m'
YLW='\033[1;33m'
RED='\033[0;31m'
PRP='\033[0;35m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="$SCRIPT_DIR/config.py"

echo ""
echo -e "${PRP}  ╔═══════════════════════════════════════╗${NC}"
echo -e "${PRP}  ║     PURPLE RAINMAKER INSTALL          ║${NC}"
echo -e "${PRP}  ║     Shawn C. Tovey, RCDD              ║${NC}"
echo -e "${PRP}  ╚═══════════════════════════════════════╝${NC}"
echo ""

# ── GUARD: already installed ──────────────────────────────────
if [ -f "$CONFIG" ]; then
    echo -e "${YLW}[!] config.py already exists — already installed.${NC}"
    echo -e "${YLW}    To update: bash update.sh${NC}"
    echo -e "${YLW}    To reinstall: delete config.py and run install.sh again.${NC}"
    echo ""
    exit 0
fi

# ── CHECK: Debian/Ubuntu/Kali only ───────────────────────────
if ! command -v apt &>/dev/null; then
    echo -e "${RED}[!] apt not found. Purple Rainmaker requires Kali/Debian/Ubuntu.${NC}"
    exit 1
fi

# ── STEP 1: SYSTEM PACKAGES ──────────────────────────────────
echo -e "${YLW}[*] Installing system packages...${NC}"
sudo apt update -qq
sudo apt install -y nmap arp-scan weasyprint python3-pip
echo -e "${GRN}[+] System packages installed.${NC}"

# ── STEP 2: PYTHON PACKAGES ──────────────────────────────────
echo -e "${YLW}[*] Installing Python packages...${NC}"
pip install -r "$SCRIPT_DIR/requirements.txt" --break-system-packages -q
echo -e "${GRN}[+] Python packages installed.${NC}"

# ── STEP 3: DIRECTORIES ──────────────────────────────────────
echo -e "${YLW}[*] Creating directories...${NC}"
mkdir -p "$SCRIPT_DIR/playbook/reports"
echo -e "${GRN}[+] Directories created.${NC}"

# ── STEP 4: SUDOERS ──────────────────────────────────────────
echo -e "${YLW}[*] Configuring sudoers...${NC}"
CURRENT_USER="${SUDO_USER:-$(whoami)}"
SUDOERS_FILE="/etc/sudoers.d/purplerainmaker"

# No wildcard — autopilot.sh reads its config from config.sh, not from arguments
sudo tee "$SUDOERS_FILE" > /dev/null << SUDOERS
# Purple Rainmaker — passwordless network scan (no wildcard arguments)
$CURRENT_USER ALL=(ALL) NOPASSWD: /bin/bash $SCRIPT_DIR/autopilot.sh
$CURRENT_USER ALL=(ALL) NOPASSWD: /usr/bin/nmap
$CURRENT_USER ALL=(ALL) NOPASSWD: /usr/sbin/arp-scan
SUDOERS

sudo chmod 440 "$SUDOERS_FILE"
echo -e "${GRN}[+] Sudoers configured for $CURRENT_USER.${NC}"

# ── STEP 4b: WRITE config.sh ─────────────────────────────────
# config.sh gives autopilot.sh the reports directory without shell args.
DEFAULT_REPORTS="$SCRIPT_DIR/playbook/reports"
cat > "$SCRIPT_DIR/config.sh" << CONFIGSH
# Purple Rainmaker shell config — generated by install.sh
# Edit REPORTS_DIR here if you change the reports location.
PR_REPORTS_DIR='${DEFAULT_REPORTS}'
CONFIGSH
echo -e "${GRN}[+] config.sh written.${NC}"

# ── STEP 5: PERMISSIONS ──────────────────────────────────────
chmod +x "$SCRIPT_DIR/autopilot.sh"
chmod +x "$SCRIPT_DIR/install.sh"
chmod +x "$SCRIPT_DIR/update.sh"
echo -e "${GRN}[+] Scripts executable.${NC}"

# ── STEP 6: START APP ─────────────────────────────────────────
echo ""
echo -e "${YLW}[*] Starting Purple Rainmaker...${NC}"
cd "$SCRIPT_DIR"
nohup python3 app.py > /tmp/purplerainmaker.log 2>&1 &
sleep 2

if pgrep -f "python3.*app.py" > /dev/null; then
    echo -e "${GRN}[+] Purple Rainmaker is running.${NC}"
    echo ""
    echo -e "${PRP}  ┌─────────────────────────────────────────┐${NC}"
    echo -e "${PRP}  │  Open your browser and go to:           │${NC}"
    echo -e "${PRP}  │  http://localhost:5000/setup            │${NC}"
    echo -e "${PRP}  │  to complete setup.                     │${NC}"
    echo -e "${PRP}  └─────────────────────────────────────────┘${NC}"
    echo ""
else
    echo -e "${RED}[!] Failed to start. Check log:${NC}"
    tail -20 /tmp/purplerainmaker.log
fi
